// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOvMXDds2_3dzAHPZLEUhX1dgbuS2bV9k',
    appId: '1:150372704362:web:164312d614ab93f8bdaa13',
    messagingSenderId: '150372704362',
    projectId: 'babyshop-5e70d',
    authDomain: 'babyshop-5e70d.firebaseapp.com',
    storageBucket: 'babyshop-5e70d.firebasestorage.app',
    measurementId: 'G-X18WETZHNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZbslTNR8p4mPOrqjHmQYDYGPOadcHprI',
    appId: '1:150372704362:android:b44c81d9f764a300bdaa13',
    messagingSenderId: '150372704362',
    projectId: 'babyshop-5e70d',
    storageBucket: 'babyshop-5e70d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAST0bmXxZRzpZYhALx16uiHTLKaQPz2I',
    appId: '1:150372704362:ios:4ee8883c20d7118cbdaa13',
    messagingSenderId: '150372704362',
    projectId: 'babyshop-5e70d',
    storageBucket: 'babyshop-5e70d.firebasestorage.app',
    iosBundleId: 'com.example.babyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAST0bmXxZRzpZYhALx16uiHTLKaQPz2I',
    appId: '1:150372704362:ios:4ee8883c20d7118cbdaa13',
    messagingSenderId: '150372704362',
    projectId: 'babyshop-5e70d',
    storageBucket: 'babyshop-5e70d.firebasestorage.app',
    iosBundleId: 'com.example.babyshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOvMXDds2_3dzAHPZLEUhX1dgbuS2bV9k',
    appId: '1:150372704362:web:455b1811d7e7856fbdaa13',
    messagingSenderId: '150372704362',
    projectId: 'babyshop-5e70d',
    authDomain: 'babyshop-5e70d.firebaseapp.com',
    storageBucket: 'babyshop-5e70d.firebasestorage.app',
    measurementId: 'G-0NBS7J8785',
  );

}