// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVOl_gEkfGFYBHsoMot2I-AXSZTbrhGk',
    appId: '1:198687950568:web:da4ff4303a7f55de15eb5d',
    messagingSenderId: '198687950568',
    projectId: 'babyshop-d4c79',
    authDomain: 'babyshop-d4c79.firebaseapp.com',
    storageBucket: 'babyshop-d4c79.firebasestorage.app',
    measurementId: 'G-DWVHRDZX1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZ5pj64g3bROKlyPQQSpMegu601Pyko0',
    appId: '1:198687950568:android:7f691866faa8148315eb5d',
    messagingSenderId: '198687950568',
    projectId: 'babyshop-d4c79',
    storageBucket: 'babyshop-d4c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_4zBv7BLOhcSQqNKliC7rVtOSCfP6BXg',
    appId: '1:198687950568:ios:af65cd438d20482d15eb5d',
    messagingSenderId: '198687950568',
    projectId: 'babyshop-d4c79',
    storageBucket: 'babyshop-d4c79.firebasestorage.app',
    iosBundleId: 'com.example.babyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_4zBv7BLOhcSQqNKliC7rVtOSCfP6BXg',
    appId: '1:198687950568:ios:af65cd438d20482d15eb5d',
    messagingSenderId: '198687950568',
    projectId: 'babyshop-d4c79',
    storageBucket: 'babyshop-d4c79.firebasestorage.app',
    iosBundleId: 'com.example.babyshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVOl_gEkfGFYBHsoMot2I-AXSZTbrhGk',
    appId: '1:198687950568:web:5f70ade46957d56615eb5d',
    messagingSenderId: '198687950568',
    projectId: 'babyshop-d4c79',
    authDomain: 'babyshop-d4c79.firebaseapp.com',
    storageBucket: 'babyshop-d4c79.firebasestorage.app',
    measurementId: 'G-RD8ZWYED3Z',
  );
}
